export const INVOICE_LABELS = {
  en: {
    invoice: "INVOICE",
    quote: "QUOTE",
    credit_note: "CREDIT NOTE",
    pro_forma: "PRO FORMA",
    delivery_note: "DELIVERY NOTE",
    sale_order: "SALE ORDER",
    issueDate: "Issue Date",
    dueDate: "Due Date",
    paymentMethod: "Payment",
    billTo: "Bill To",
    description: "Description",
    qty: "Qty",
    price: "Price",
    vat: "VAT",
    total: "Total",
    subtotal: "Subtotal",
    stampDuty: "Stamp Duty",
    vatTotal: "VAT Total",
    grandTotal: "Grand Total",
    notes: "Notes",
    amountInWords: "Amount in words",
    legalFooter: "Invoice issued in accordance with Law 04-02 and Executive Decree 05-468 regarding commercial practices in Algeria.",
    thankYou: "Thank you for your business.",
    autoEntrepreneur: "VAT not applicable – Auto-Entrepreneur (IFU).",
    flatRate: "VAT not applicable – Flat rate regime (IFU).",
    sellerNif: "NIF",
    sellerRc: "RC",
    sellerAi: "AI",
    sellerNis: "NIS",
    sellerCapital: "Capital",
    tel: "Tel",
    email: "Email",
    signature: "Signature",
  },
  fr: {
    invoice: "FACTURE",
    quote: "DEVIS",
    credit_note: "AVOIR",
    pro_forma: "FACTURE PRO FORMA",
    delivery_note: "BON DE LIVRAISON",
    sale_order: "BON DE COMMANDE",
    issueDate: "Date d'émission",
    dueDate: "Date d'échéance",
    paymentMethod: "Paiement",
    billTo: "Facturé à",
    description: "Désignation",
    qty: "Qté",
    price: "Prix U.",
    vat: "TVA",
    total: "Total",
    subtotal: "Sous-total",
    stampDuty: "Droit de Timbre",
    vatTotal: "Total TVA",
    grandTotal: "Total TTC",
    notes: "Notes",
    amountInWords: "Arrêté la présente facture à la somme de",
    legalFooter: "",
    thankYou: "",
    autoEntrepreneur: "TVA non applicable – Auto-Entrepreneur (IFU).",
    flatRate: "TVA non applicable – Régime forfaitaire (IFU).",
    sellerNif: "NIF",
    sellerRc: "RC",
    sellerAi: "AI",
    sellerNis: "NIS",
    sellerCapital: "Capital",
    tel: "Tél",
    email: "Email",
    signature: "Signature",
  },
  ar: {
    invoice: "فاتورة",
    quote: "عرض سعر",
    credit_note: "إشعار دائن",
    pro_forma: "فاتورة أولية",
    delivery_note: "وصل تسليم",
    sale_order: "طلب بيع",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    paymentMethod: "طريقة الدفع",
    billTo: "العميل",
    description: "البيان",
    qty: "الكمية",
    price: "السعر",
    vat: "ر.ق.م",
    total: "المجموع",
    subtotal: "المجموع الفرعي",
    stampDuty: "حق الطابع",
    vatTotal: "مجموع الرسم",
    grandTotal: "المجموع الكلي",
    notes: "ملاحظات",
    amountInWords: "توقف هذا السند عند مبلغ",
    legalFooter: "فاتورة محررة طبقا للقانون 04-02 والمرسوم التنفيذي 05-468 المتعلق بالممارسات التجارية في الجزائر.",
    thankYou: "شكرا لتعاملكم معنا.",
    autoEntrepreneur: "إعفاء من الرسم على القيمة المضافة - مقاول ذاتي.",
    flatRate: "إعفاء من الرسم على القيمة المضافة - نظام جزافي.",
    sellerNif: "ر.ت.ج",
    sellerRc: "س.ت",
    sellerAi: "م.ض",
    sellerNis: "ر.ت.إ",
    sellerCapital: "رأس المال",
    tel: "هاتف",
    email: "بريد إلكتروني",
    signature: "التوقيع",
  }
} as const;

export type InvoiceLanguage = keyof typeof INVOICE_LABELS;