export const PRICING_PLANS = {
  en: [
    {
      id: "free",
      name: "Auto-Entrepreneur",
      description: "Perfect for freelancers. 3 months free trial.",
      price: "12,000 DZD",
      originalPrice: "24,000 DZD",
      period: "/year",
      billingNote: "Billed annually",
      features: [
        "Invoicing",
        "Transactions",
        "Role Management",
        "Digital Stamp & Signature",
        "Quote Conversion",
        "Expense Management",
        "Email Sending",
        "Online Support",
      ],
      userCount: "1 User",
      storage: "1 GB Storage",
      cta: "Start Free Trial",
      popular: false,
    },
    {
      id: "startup",
      name: "Startup",
      description: "For small teams. 1 month free trial.",
      price: "39,000 DZD",
      originalPrice: undefined,
      period: "/year",
      billingNote: "Billed annually",
      features: [
        "Invoicing",
        "Transactions",
        "Role Management",
        "Digital Stamp & Signature",
        "Quote Conversion",
        "Expense Management",
        "Email Sending",
        "Online Support",
      ],
      userCount: "3 Users",
      storage: "1 GB Storage",
      cta: "Start Free Trial",
      popular: false,
    },
    {
      id: "pro",
      name: "Small Business",
      description: "For growing businesses. 1 month free trial.",
      price: "49,000 DZD",
      originalPrice: undefined,
      period: "/year",
      billingNote: "Billed annually",
      features: [
        "Invoicing",
        "Transactions",
        "Role Management",
        "Digital Stamp & Signature",
        "Quote Conversion",
        "Expense Management",
        "Email Sending",
        "Online Support",
      ],
      userCount: "6 Users",
      storage: "2 GB Storage",
      cta: "Start Free Trial",
      popular: true,
    },
    {
      id: "premium",
      name: "Premium",
      description: "For established companies. 1 month free trial.",
      price: "69,000 DZD",
      originalPrice: undefined,
      period: "/year",
      billingNote: "Billed annually",
      features: [
        "Invoicing",
        "Transactions",
        "Role Management",
        "Digital Stamp & Signature",
        "Quote Conversion",
        "Expense Management",
        "Email Sending",
        "Online Support",
      ],
      userCount: "10 Users",
      storage: "4 GB Storage",
      cta: "Start Free Trial",
      popular: false,
    },
    {
      id: "enterprise",
      name: "Enterprise",
      description: "For large organizations with specific needs.",
      price: "Custom",
      originalPrice: undefined,
      period: "/year",
      billingNote: "Custom billing",
      features: [
        "Unlimited Users",
        "Unlimited Storage",
        "Custom Integrations",
        "Dedicated Support",
        "SLA",
        "On-premise Option",
      ],
      userCount: "Unlimited Users",
      storage: "Unlimited Storage",
      cta: "Contact Sales",
      popular: false,
    },
  ],
  fr: [
    {
      id: "free",
      name: "Auto-Entrepreneur",
      description: "Parfait pour les freelances. 3 mois d'essai gratuit.",
      price: "12 000 DZD",
      originalPrice: "24 000 DZD",
      period: "/an",
      billingNote: "Facturation annuelle",
      features: [
        "Facturation",
        "Transactions",
        "Gestion de rôle",
        "Cachet et signature numérique",
        "Conversion de devis",
        "Gestion de dépenses",
        "Envoi par email",
        "Support en ligne",
      ],
      userCount: "1 Utilisateur",
      storage: "1 Go de stockage",
      cta: "Essai gratuit",
      popular: false,
    },
    {
      id: "startup",
      name: "Startup",
      description: "Pour les petites équipes. 1 mois d'essai gratuit.",
      price: "39 000 DZD",
      originalPrice: undefined,
      period: "/an",
      billingNote: "Facturation annuelle",
      features: [
        "Facturation",
        "Transactions",
        "Gestion de rôle",
        "Cachet et signature numérique",
        "Conversion de devis",
        "Gestion de dépenses",
        "Envoi par email",
        "Support en ligne",
      ],
      userCount: "3 Utilisateurs",
      storage: "1 Go de stockage",
      cta: "Essai gratuit",
      popular: false,
    },
    {
      id: "pro",
      name: "Small Business",
      description: "Pour les entreprises en croissance. 1 mois d'essai gratuit.",
      price: "49 000 DZD",
      originalPrice: undefined,
      period: "/an",
      billingNote: "Facturation annuelle",
      features: [
        "Facturation",
        "Transactions",
        "Gestion de rôle",
        "Cachet et signature numérique",
        "Conversion de devis",
        "Gestion de dépenses",
        "Envoi par email",
        "Support en ligne",
      ],
      userCount: "6 Utilisateurs",
      storage: "2 Go de stockage",
      cta: "Essai gratuit",
      popular: true,
    },
    {
      id: "premium",
      name: "Premium",
      description: "Pour les entreprises établies. 1 mois d'essai gratuit.",
      price: "69 000 DZD",
      originalPrice: undefined,
      period: "/an",
      billingNote: "Facturation annuelle",
      features: [
        "Facturation",
        "Transactions",
        "Gestion de rôle",
        "Cachet et signature numérique",
        "Conversion de devis",
        "Gestion de dépenses",
        "Envoi par email",
        "Support en ligne",
      ],
      userCount: "10 Utilisateurs",
      storage: "4 Go de stockage",
      cta: "Essai gratuit",
      popular: false,
    },
    {
      id: "enterprise",
      name: "Entreprise",
      description: "Pour les grandes organisations avec des besoins spécifiques.",
      price: "Sur mesure",
      originalPrice: undefined,
      period: "/an",
      billingNote: "Facturation personnalisée",
      features: [
        "Utilisateurs illimités",
        "Stockage illimité",
        "Intégrations personnalisées",
        "Support dédié",
        "SLA",
        "Option sur site",
      ],
      userCount: "Utilisateurs illimités",
      storage: "Stockage illimité",
      cta: "Contacter les ventes",
      popular: false,
    },
  ],
  ar: [
    {
      id: "free",
      name: "مقاول ذاتي",
      description: "مثالي للمستقلين. تجربة مجانية لمدة 3 أشهر.",
      price: "12٬000 دج",
      originalPrice: "24٬000 دج",
      period: "/سنة",
      billingNote: "فوترة سنوية",
      features: [
        "الفوترة",
        "المعاملات",
        "إدارة الأدوار",
        "الختم والتوقيع الرقمي",
        "تحويل عروض الأسعار",
        "إدارة المصاريف",
        "إرسال عبر البريد الإلكتروني",
        "دعم عبر الإنترنت",
      ],
      userCount: "مستخدم واحد",
      storage: "1 جيغابايت تخزين",
      cta: "ابدأ مجانًا",
      popular: false,
    },
    {
      id: "startup",
      name: "ناشئة",
      description: "للفرق الصغيرة. تجربة مجانية لمدة شهر.",
      price: "39٬000 دج",
      originalPrice: undefined,
      period: "/سنة",
      billingNote: "فوترة سنوية",
      features: [
        "الفوترة",
        "المعاملات",
        "إدارة الأدوار",
        "الختم والتوقيع الرقمي",
        "تحويل عروض الأسعار",
        "إدارة المصاريف",
        "إرسال عبر البريد الإلكتروني",
        "دعم عبر الإنترنت",
      ],
      userCount: "3 مستخدمين",
      storage: "1 جيغابايت تخزين",
      cta: "ابدأ الآن",
      popular: false,
    },
    {
      id: "pro",
      name: "Small Business",
      description: "للشركات النامية. تجربة مجانية لمدة شهر.",
      price: "49٬000 دج",
      originalPrice: undefined,
      period: "/سنة",
      billingNote: "فوترة سنوية",
      features: [
        "الفوترة",
        "المعاملات",
        "إدارة الأدوار",
        "الختم والتوقيع الرقمي",
        "تحويل عروض الأسعار",
        "إدارة المصاريف",
        "إرسال عبر البريد الإلكتروني",
        "دعم عبر الإنترنت",
      ],
      userCount: "6 مستخدمين",
      storage: "2 جيغابايت تخزين",
      cta: "جرّب مجانًا",
      popular: true,
    },
    {
      id: "premium",
      name: "Premium",
      description: "للشركات القائمة. تجربة مجانية لمدة شهر.",
      price: "69٬000 دج",
      originalPrice: undefined,
      period: "/سنة",
      billingNote: "فوترة سنوية",
      features: [
        "الفوترة",
        "المعاملات",
        "إدارة الأدوار",
        "الختم والتوقيع الرقمي",
        "تحويل عروض الأسعار",
        "إدارة المصاريف",
        "إرسال عبر البريد الإلكتروني",
        "دعم عبر الإنترنت",
      ],
      userCount: "10 مستخدمين",
      storage: "4 جيغابايت تخزين",
      cta: "احصل على بريميوم",
      popular: false,
    },
    {
      id: "enterprise",
      name: "مؤسسة",
      description: "للمؤسسات الكبيرة ذات الاحتياجات الخاصة.",
      price: "حسب الطلب",
      originalPrice: undefined,
      period: "/سنة",
      billingNote: "فوترة مخصصة",
      features: [
        "مستخدمين غير محدودين",
        "تخزين غير محدود",
        "تكاملات مخصصة",
        "دعم مخصص",
        "اتفاقية مستوى الخدمة",
        "خيار محلي",
      ],
      userCount: "مستخدمين غير محدودين",
      storage: "تخزين غير محدود",
      cta: "اتصل بالمبيعات",
      popular: false,
    },
  ],
} as const;

export type PlanId = "free" | "startup" | "pro" | "premium" | "enterprise";